name: CBOMKit Scan & Push to Wazuh

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # Run daily at 3 UTC

jobs:
  cbom_scan:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate CBOM using PQCA Action
        uses: PQCA/cbomkit-action@v2.1.0
        id: cbom

      - name: Upload CBOM JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: cbom-report
          path: ${{ steps.cbom.outputs.pattern }}

      - name: Send CBOM to Wazuh (Elasticsearch)
        if: always()
        env:
          ELASTIC_URL: ${{ secrets.ELASTIC_URL }}
          ELASTIC_USER: ${{ secrets.ELASTIC_USER }}
          ELASTIC_PASS: ${{ secrets.ELASTIC_PASS }}
          CBOM_FILE: ${{ steps.cbom.outputs.pattern }}
        run: |
          pip install requests
          python3 <<EOF
import json, requests, os

with open(os.environ["CBOM_FILE"]) as f:
    cbom = json.load(f)

for asset in cbom.get("cryptographic_assets", []):
    doc = {
        "repo": "${{ github.repository }}",
        "file": asset.get("location"),
        "algorithm": asset.get("algorithm"),
        "library": asset.get("library"),
        "pq_safe": asset.get("pq_safe", False),
        "risk_level": asset.get("risk_level", "unknown"),
        "timestamp": "${{ github.run_started_at }}"
    }
    res = requests.post(
        f"{os.environ['ELASTIC_URL']}/cbomkit-reports/_doc",
        auth=(os.environ["ELASTIC_USER"], os.environ["ELASTIC_PASS"]),
        headers={"Content-Type": "application/json"},
        json=doc
    )
    print(res.status_code, res.text)
EOF
