name: CBOMKit Scan and Push to Wazuh

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  cbom_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CBOMKit and generate report
        run: |
          docker run --rm -v ${{ github.workspace }}:/repo ghcr.io/ibm/cbomkit:latest /repo > cbom_raw.json

      - name: Install Python requests
        run: pip install requests

      - name: Write Python script to push CBOM to Elasticsearch
        run: |
          echo "import json" > push_cbom_to_es.py
          echo "import requests" >> push_cbom_to_es.py
          echo "import os" >> push_cbom_to_es.py
          echo "" >> push_cbom_to_es.py
          echo "with open('cbom_raw.json') as f:" >> push_cbom_to_es.py
          echo "    cbom = json.load(f)" >> push_cbom_to_es.py
          echo "" >> push_cbom_to_es.py
          echo "assets = cbom.get('cryptographic_assets', [])" >> push_cbom_to_es.py
          echo "url = os.environ['ELASTIC_URL']" >> push_cbom_to_es.py
          echo "auth = (os.environ['ELASTIC_USER'], os.environ['ELASTIC_PASS'])" >> push_cbom_to_es.py
          echo "" >> push_cbom_to_es.py
          echo "for asset in assets:" >> push_cbom_to_es.py
          echo "    doc = {" >> push_cbom_to_es.py
          echo "        'repo': os.environ.get('GITHUB_REPOSITORY')," >> push_cbom_to_es.py
          echo "        'file': asset.get('location')," >> push_cbom_to_es.py
          echo "        'algorithm': asset.get('algorithm')," >> push_cbom_to_es.py
          echo "        'library': asset.get('library')," >> push_cbom_to_es.py
          echo "        'pq_safe': asset.get('pq_safe', False)," >> push_cbom_to_es.py
          echo "        'risk_level': asset.get('risk_level', 'unknown')," >> push_cbom_to_es.py
          echo "        'scanner': cbom.get('scanner', '')," >> push_cbom_to_es.py
          echo "        'generated_at': cbom.get('bomTimestamp', '')" >> push_cbom_to_es.py
          echo "    }" >> push_cbom_to_es.py
          echo "    res = requests.post(f'{url}/cbomkit-reports/_doc', json=doc, auth=auth)" >> push_cbom_to_es.py
          echo "    print(res.status_code, res.text)" >> push_cbom_to_es.py

      - name: Run push script
        env:
          ELASTIC_URL: ${{ secrets.ELASTIC_URL }}
          ELASTIC_USER: ${{ secrets.ELASTIC_USER }}
          ELASTIC_PASS: ${{ secrets.ELASTIC_PASS }}
        run: python3 push_cbom_to_es.py
