name: Generate CBOM

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Generate CBOM
        uses: PQCA/cbomkit-action@v2.1.0
        id: cbom

      - name: Upload CBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: cbom
          path: cbom/
