name: CBOMKit Scan and Push to Wazuh

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  cbom-scan:
    runs-on: ubuntu-latest
    name: CBOM generation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean package -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create CBOM
        uses: PQCA/cbomkit-action@v2.1.0
        id: cbom

      - name: Upload CBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: cbom-report
          path: ${{ steps.cbom.outputs.pattern }}
          if-no-files-found: warn

  push-cbom:
    needs: cbom-scan
    runs-on: ubuntu-latest
    name: Push CBOM to Elasticsearch

    permissions:
      contents: read

    steps:
      - name: Download CBOM artifact
        uses: actions/download-artifact@v4
        with:
          name: cbom-report

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: pip install requests

      - name: Push CBOM to Elasticsearch
        env:
          ELASTIC_URL: ${{ secrets.ELASTIC_URL }}
          ELASTIC_USER: ${{ secrets.ELASTIC_USER }}
          ELASTIC_PASS: ${{ secrets.ELASTIC_PASS }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python3 - << 'EOF'
          import json, os, glob, requests

          # Load all CBOM JSON files from the artifact
          files = glob.glob("*.json")
          if not files:
              print("No CBOM files found.")
              exit(1)

          url = os.environ['ELASTIC_URL']
          auth = (os.environ['ELASTIC_USER'], os.environ['ELASTIC_PASS'])
          repo = os.environ['GITHUB_REPOSITORY']

          for fname in files:
              with open(fname) as f:
                  cbom = json.load(f)

              assets = cbom.get('cryptographic_assets', [])
              for asset in assets:
                  doc = {
                      'repo': repo,
                      'file': asset.get('location'),
                      'algorithm': asset.get('algorithm'),
                      'library': asset.get('library'),
                      'pq_safe': asset.get('pq_safe', False),
                      'risk_level': asset.get('risk_level', 'unknown'),
                      'scanner': cbom.get('scanner', ''),
                      'generated_at': cbom.get('bomTimestamp', '')
                  }
                  res = requests.post(f'{url}/cbomkit-reports/_doc', json=doc, auth=auth)
                  print(fname, res.status_code, res.text)
          EOF
