name: Generate CBOM

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build (e.g., Java, Python)
        # Example for Java:
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Create CBOM
        uses: PQCA/cbomkit-action@v2.1.0
        id: cbom

      - name: Save CBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: CBOM
          path: ${{ steps.cbom.outputs.pattern }}
          if-no-files-found: warn
