- name: Format & Push to Elasticsearch
  env:
    ELASTIC_URL: ${{ secrets.ELASTIC_URL }}
    ELASTIC_USER: ${{ secrets.ELASTIC_USER }}
    ELASTIC_PASS: ${{ secrets.ELASTIC_PASS }}
  run: |
    pip install requests
    cat <<'EOF' > cbom_push.py
import json, requests, os

with open("cbom_raw.json") as f:
    cbom = json.load(f)

assets = cbom.get("cryptographic_assets", [])
url = os.environ["ELASTIC_URL"]
auth = (os.environ["ELASTIC_USER"], os.environ["ELASTIC_PASS"])

for item in assets:
    doc = {
        "repo": os.environ.get("GITHUB_REPOSITORY"),
        "file": item.get("location"),
        "algorithm": item.get("algorithm"),
        "library": item.get("library"),
        "pq_safe": item.get("pq_safe", False),
        "risk_level": item.get("risk_level", "unknown"),
        "timestamp": os.environ.get("GITHUB_EVENT_TIME", "")
    }
    res = requests.post(f"{url}/cbomkit-reports/_doc", json=doc, auth=auth)
    print(res.status_code, res.text)
EOF
    python3 cbom_push.py
